apiVersion: authorization.azure.upbound.io/v1beta1
kind: RoleAssignment
metadata:
  name: qa-krce-bwjang-log-aks-role-privatedns
spec:
  forProvider:
    principalId: "22df9410-761b-4375-b46b-54f553a2f6f1"
    roleDefinitionName: Contributor
    scope: "/subscriptions/e1309911-b426-422a-899e-bf7fabea02a3/resourceGroups/mc_qa-krce-test-bwjang-aks-rg_qa-krce-test-bwjang-aks_koreacentral"
  providerConfigRef:
    name: workload-identity-provider-config
---
apiVersion: authorization.azure.upbound.io/v1beta1
kind: RoleAssignment
metadata:
  name: qa-uset-gasp-log-aks-role-subnet
spec:
  forProvider:
    principalId: "22df9410-761b-4375-b46b-54f553a2f6f1"
    roleDefinitionName: Contributor
    scope: "/subscriptions/e1309911-b426-422a-899e-bf7fabea02a3/resourceGroups/qa-krce-test-bwjang-aks-rg/providers/Microsoft.Network/virtualNetworks/qa-krce-test-bwjang-aks-vnet/subnets/crossplane-aks-subnet"
  providerConfigRef:
    name: workload-identity-provider-config