apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbwjangkube-comp
  namespace: crossplane-system
spec:
  compositeTypeRef:
    apiVersion: onestore.net/v1alpha1
    kind: xbwjangkube
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: ResourceGroup
        base:
          apiVersion: azure.upbound.io/v1beta1
          kind: ResourceGroup
          spec:
            providerConfigRef:
              name: workload-identity-provider-config  
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.name
              strategy: string
              string:
                fmt: "%s-rg"
            toFieldPath: "metadata.name"
          - fromFieldPath: "spec.location"
            toFieldPath: "spec.forProvider.location"
          - type: ToCompositeFieldPath
            fromFieldPath: status.atProvider.id
            toFieldPath: status.resourceGroupId
      - name: UserAssignedIdentity
        base:
          apiVersion: managedidentity.azure.upbound.io/v1beta1
          kind: UserAssignedIdentity
          spec:
            providerConfigRef:
              name: workload-identity-provider-config  
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.name
              strategy: string
              string:
                fmt: "%s-managed-id"
            toFieldPath: "metadata.name"
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.name
              strategy: string
              string:
                fmt: "%s-managed-id"
            toFieldPath: "spec.forProvider.name"
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.name
              strategy: string
              string:
                fmt: "%s-rg"
            toFieldPath: "spec.forProvider.resourceGroupName"
          - fromFieldPath: "spec.location"
            toFieldPath: "spec.forProvider.location"
          - type: ToCompositeFieldPath
            fromFieldPath: status.atProvider.id
            toFieldPath: status.managedIdentityId
          - type: ToCompositeFieldPath
            fromFieldPath: status.atProvider.principalId
            toFieldPath: status.principalId
      - name: RoleAssignmentForSubnet
        base:
          apiVersion: authorization.azure.upbound.io/v1beta1
          kind: RoleAssignment
          spec:
            providerConfigRef:
              name: workload-identity-provider-config  
            forProvider:
              roleDefinitionName: "Contributor" 
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.name
              strategy: string
              string:
                fmt: "%s-role-subnet"
            toFieldPath: "metadata.name"
          - fromFieldPath: "spec.subnetid"
            toFieldPath: "spec.forProvider.scope"
          - type: FromCompositeFieldPath # 생성된 리소스의 status에서 값 뺴오는 방법 -2
            fromFieldPath: status.principalId
            toFieldPath: spec.forProvider.principalId
      - name: RoleAssignmentForRg
        base:
          apiVersion: authorization.azure.upbound.io/v1beta1
          kind: RoleAssignment
          spec:
            providerConfigRef:
              name: workload-identity-provider-config  
            forProvider:
              roleDefinitionName: "Contributor" 
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.name
              strategy: string
              string:
                fmt: "%s-role-rg"
            toFieldPath: "metadata.name"
          - type: FromCompositeFieldPath # 생성된 리소스의 status에서 값 뺴오는 방법 -2
            fromFieldPath: status.resourceGroupId
            toFieldPath: spec.forProvider.scope
          - type: FromCompositeFieldPath # 생성된 리소스의 status에서 값 뺴오는 방법 -2
            fromFieldPath: status.principalId
            toFieldPath: spec.forProvider.principalId
      - name: kubernetesCluster
        base:
          apiVersion: containerservice.azure.upbound.io/v1beta1
          kind: KubernetesCluster
          spec:
            providerConfigRef:
              name: workload-identity-provider-config  
            forProvider:
              azurePolicyEnabled: true
              networkProfile:
              - networkPlugin: azure
                networkPolicy: azure
              defaultNodePool:
                - enableAutoScaling: true
                  onlyCriticalAddonsEnabled: false
                  osDiskType: Managed
                  type: VirtualMachineScaleSets
                  zones:
                  - "1"
                  - "2"
                  - "3"
              publicNetworkAccessEnabled: false
              identity:
              - type: UserAssigned
              privateClusterEnabled: true
              azureActiveDirectoryRoleBasedAccessControl:
                - azureRbacEnabled: false
                  managed: true
              localAccountDisabled: true
              oidcIssuerEnabled: true
              workloadIdentityEnabled: true
              skuTier: Standard
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.name
              strategy: string
              string:
                fmt: "%s-aks"
            toFieldPath: "metadata.name"
          - fromFieldPath: "spec.k8sVersion"
            toFieldPath: "spec.forProvider.kubernetesVersion"
          - fromFieldPath: "spec.nodePoolName"
            toFieldPath: "spec.forProvider.defaultNodePool[0].name"
          - fromFieldPath: "spec.nodeCount"
            toFieldPath: "spec.forProvider.defaultNodePool[0].nodeCount"
          - fromFieldPath: "spec.maxCount"
            toFieldPath: "spec.forProvider.defaultNodePool[0].maxCount"
          - fromFieldPath: "spec.minCount"
            toFieldPath: "spec.forProvider.defaultNodePool[0].minCount"
          - fromFieldPath: "spec.nodeSize"
            toFieldPath: "spec.forProvider.defaultNodePool[0].nodeSize"
          - fromFieldPath: "spec.subnetid"
            toFieldPath: "spec.forProvider.defaultNodePool[0].vnetSubnetId"
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.name
              strategy: string
              string:
                fmt: "%s-aks"
            toFieldPath: "spec.forProvider.dnsPrefix"
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.name
              strategy: string
              string:
                fmt: "%s-rg"
            toFieldPath: "spec.forProvider.nodeResourceGroup"
          - type: FromCompositeFieldPath # 생성된 리소스의 status에서 값 뺴오는 방법 -2
            fromFieldPath: status.managedIdentityId
            toFieldPath: spec.forProvider.identity[0].identityIds[0]
          - fromFieldPath: "spec.k8sAdmingroup"
            toFieldPath: "spec.forProvider.azureActiveDirectoryRoleBasedAccessControl[0].adminGroupObjectIds[0]"
          - fromFieldPath: "spec.location"
            toFieldPath: "spec.forProvider.location"
            transforms:
              - type: map
                map:
                  "Korea Central": "koreacentral"
                  "East US": "eastus"
                  "West Europe": "westeurope"
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.name
              strategy: string
              string:
                fmt: "%s-rg"
            toFieldPath: "spec.forProvider.resourceGroupName"
  - step: detect-readiness
    functionRef:
      name: function-auto-ready
  - step: sequence-creation
    functionRef:
      name: function-sequencer
    input:
      apiVersion: sequencer.fn.crossplane.io/v1beta1
      kind: Input
      rules:
        - sequence:
          - ResourceGroup
          - UserAssignedIdentity
          - RoleAssignmentForSubnet
          - RoleAssignmentForRg
          - kubernetesCluster

