apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbwjangkube-comp
  namespace: crossplane-system
spec:
  compositeTypeRef:
    apiVersion: onestore.net/v1alpha1
    kind: xbwjangkube
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: ResourceGroup
        base:
          apiVersion: azure.upbound.io/v1beta1
          kind: ResourceGroup
          spec:
            providerConfigRef:
              name: workload-identity-provider-config  
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.name
              strategy: string
              string:
                fmt: "%s-rg"
            toFieldPath: "metadata.name"
          - fromFieldPath: "spec.location"
            toFieldPath: "spec.forProvider.location"
      - name: UserAssignedIdentity
        base:
          apiVersion: managedidentity.azure.upbound.io/v1beta1
          kind: UserAssignedIdentity
          spec:
            providerConfigRef:
              name: workload-identity-provider-config  
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.name
              strategy: string
              string:
                fmt: "%s-managed-id"
            toFieldPath: "metadata.name"
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.name
              strategy: string
              string:
                fmt: "%s-managed-id"
            toFieldPath: "spec.forProvider.name"
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.name
              strategy: string
              string:
                fmt: "%s-rg"
            toFieldPath: "spec.forProvider.resourceGroupName"
          - fromFieldPath: "spec.location"
            toFieldPath: "spec.forProvider.location"
          - type: ToCompositeFieldPath
            fromFieldPath: status.atProvider.principalId
            toFieldPath: status.principalId
      - name: RoleAssignment
        base:
          apiVersion: authorization.azure.upbound.io/v1beta1
          kind: RoleAssignment
          spec:
            providerConfigRef:
              name: workload-identity-provider-config  
            forProvider:
              roleDefinitionName: "Contributor" 
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.name
              strategy: string
              string:
                fmt: "%s-role-subnet"
            toFieldPath: "metadata.name"
          - fromFieldPath: "spec.vnetid"
            toFieldPath: "spec.forProvider.scope"
          - type: FromCompositeFieldPath # 생성된 리소스의 status에서 값 뺴오는 방법 -2
            fromFieldPath: status.principalId
            toFieldPath: spec.forProvider.principalId
  - step: detect-readiness
    functionRef:
      name: function-auto-ready
  - step: sequence-creation
    functionRef:
      name: function-sequencer
    input:
      apiVersion: sequencer.fn.crossplane.io/v1beta1
      kind: Input
      rules:
        - sequence:
          - ResourceGroup
          - UserAssignedIdentity
          - RoleAssignment
# ---
# apiVersion: example.org/v1alpha1
# kind: xMyBuckets
# metadata:
#   name: my-buckets
# spec:
#   location: Korea Central
