apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: xbwjangkubes.onestore.net
spec:
  group: onestore.net
  names:
    kind: xbwjangkube
    plural: xbwjangkubes
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: A ArgocdCluster is a composite resource that represents a K8S Cluster with Wordpress Installed
          type: object
          properties:
            spec:
              type: object
              required:
                - location
                - name
                - nodeCount
              properties:
                vnetid:
                  type: string
                  description: testScope
                location:
                  type: string
                  description: Region
                name:
                  type: string
                  minLength: 3            
                  maxLength: 25           
                  pattern: "^[a-z0-9-]+$"
                  description: Name of the K8S Cluster
                nodeCount:
                  type: integer            
                  description: "Number of nodes in the cluster"
                  minimum: 1              
                  maximum: 10             
                  default: 2
                enableAutoScaling:
                  type: boolean            
                  description: "Enable auto-scaling"
                  default: true
            status: # 생성된 리소스의 status에서 값 뺴오는 방법 -1 
              type: object
              properties:
                principalId:
                  description: managedIdentityPrincipalID
                  type: string
                resourceGroupId:
                  description: resourceGroupId
                  type: string